
- block:
  - name: 创建目录
    file:
      path: "{{ item }}"
      state: directory
      mode: 0644
    with_items:
      - "{{ k8s_pki_dir }}"
      - "{{ manifest_dir }}"

  - name: 获取 kubernetes ca 证书
    slurp:
      src: "{{ item }}"
    with_items:
      - "{{ kubernetes_ca }}"
      - "{{ kubernetes_etc_dir }}/bootstrap-kubelet.conf"
    register: slurp_kubernetes_ca_cert
    run_once: true
    delegate_to: "{{ (groups['kube_masters'] | difference(groups['delete_masters']) | unique | first) }}"

  - name: 恢复 kubernetes ca 证书
    copy:
      dest: "{{ item.source }}"
      content: "{{ item.content | b64decode }}"
      owner: root
      group: root
      mode: 0644
    no_log: true
    with_items: "{{ slurp_kubernetes_ca_cert.results }}"
  when: startup != 'kubeadm'
