- block:
  - name: 初始化 {{ lb_mode }} 配置
    include_tasks: _common.yml

  - name: 启动 kubelet, bootstrap lb 服务
    systemd:
      name: kubelet
      daemon_reload: yes
      state: restarted
      enabled: yes
    register: started_kubelet
    until: started_kubelet is succeeded
    retries: 3
    delay: "{{ retry_stagger }}"

  - name: 以轮询的方式等待 {{ lb_mode }} 启动完成
    shell: >
      nc -z -w 3 127.0.0.1 {{ lb_secure_port }};
    register: lb_status
    until: lb_status.rc == 0
    retries: 8
    delay: 15

  - name: 以轮询的方式等待 keepalived 启动完成
    shell: >
      nc -z -w 3 {{ lb_apiserver_ip | trim }} {{ lb_secure_port }};
    register: keepalived_status
    until: keepalived_status.rc == 0
    retries: 5
    delay: 15
  when:
  - lb_mode != "kube-vip"
  - lb_mode != "kube-lvscare"
  - groups['kube_masters'] | length > 1
  - inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']) | unique)
