- block:
  - name: 初始化 {{ lb_mode }} 配置
    include_tasks: _common.yml

  - name: 确保 kubelet 除临时配置外, 暂无其他配置
    when:
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ systemd_service_dir }}/kubelet.service.d/10-kubeadm.conf"
      - "{{ systemd_service_dir }}/kubelet.service.d/11-container-runtime.conf"
      - "{{ systemd_service_dir }}/kubelet.service.d/12-cgroup.conf"

  - name: 启动 kubelet, bootstrap lb 服务
    systemd:
      name: kubelet
      daemon_reload: yes
      state: restarted
      enabled: yes
    register: started_kubelet
    until: started_kubelet is succeeded
    retries: 3
    delay: "{{ retry_stagger }}"

  - name: 以轮询的方式等待 {{ lb_mode }} 启动完成
    shell: >
      ip a | grep {{ lb_apiserver_ip }}
    register: lb_status
    until: lb_status.rc == 0
    retries: 8
    delay: 15
  when:
  - lb_mode == "kube-lvscare"
  - inventory_hostname in (groups['kube_cluster'] | difference(groups['delete_masters']) | difference(groups['delete_nodes']) | unique)
