- name: 获取当前 {{ lb_mode }} 服务运行状态
  shell: >
    lb_running_num=0;
    lb_srvs='{{ lb_mode }} keepalived';
    for lb in ${lb_srvs};
    do
      {% if container_runtime == 'docker' -%}
      [ `docker ps --filter name=k8s_lb-${lb}.* --filter status=running | wc -l` -eq 2 ] && lb_running_num=`expr $lb_running_num + 1`;
      {% elif container_runtime == 'containerd' -%}
      [ `crictl ps --name=lb-${lb}.* --state running | wc -l` -eq 2 ] && lb_running_num=`expr $lb_running_num + 1`;
      {%- endif -%}
    done;
    {% if lb_mode != "kube-vip" and lb_mode != "kube-lvscare" %}
    if [ $lb_running_num -eq 2 ];then
      lb_running=true
    else
      lb_running=false
    fi;
    {% else %}
    if [ $lb_running_num -eq 1 ];then
      lb_running=true
    else
      lb_running=false
    fi;
    {% endif %}
    echo $lb_running
  register: lb_running

- block:
  - name: 添加 kube-apiserver 域名到 hosts 文件中
    blockinfile:
      path: /etc/hosts
      block: |-
        {% for domain in kube_master_external_domain.split(',') %}
        {{ lb_apiserver_ip }} {{ domain | trim }}
        {% endfor %}
      mode: 0644
      state: present
      create: yes
      backup: yes
      marker: "# Ansible kube-apiserver domain {mark}"

  - name: 确认 kubelet 暂无其他配置
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ systemd_service_dir }}/kubelet.service.d/10-kubeadm.conf"
      - "{{ systemd_service_dir }}/kubelet.service.d/11-container-runtime.conf"
      - "{{ systemd_service_dir }}/kubelet.service.d/12-cgroup.conf"

  - name: 安装 kube-lvscare
    when:
    - lb_mode == "kube-lvscare"
    - "inventory_hostname in (groups['kube_cluster'] | difference(groups['delete_masters']) | difference(groups['delete_nodes']) | unique)"
    include_tasks: lvscare_ha.yaml

  - name: 安装 kube-vip
    when:
    - lb_mode == "kube-vip"
    - inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']) | unique)
    include_tasks: vip_ha.yaml

  - name: 安装 keepalived 和 {{ lb_mode }}
    when:
    - lb_mode != "kube-vip"
    - lb_mode != "kube-lvscare"
    - inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']) | unique)
    include_tasks: keepalived_ha.yaml

  - name: 停止 kubelet
    when: lb_mode != "kube-vip"
    systemd:
      name: kubelet
      daemon_reload: yes
      state: stopped
      enabled: yes

  - name: 移除 kubelet 临时配置文件
    when: lb_mode != "kube-vip"
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ systemd_service_dir }}/kubelet.service.d/00-kubelet-override.conf"
      - "{{ kubelet_data_dir }}/config.yaml"
      - "{{ kubelet_data_dir }}/cpu_manager_state"
      - "{{ kubelet_data_dir }}/memory_manager_state"
  when: not lb_running.stdout | bool
