- block:
  - name: master 节点渲染相关配置文件
    template:
      src: "{{ item.src }}.j2"
      dest: "{{ item.dest }}"
      owner: "root"
      group: "root"
      mode: "0644"
    with_items:
      - { src: "logrotate/kube-apiserver", dest: "/etc/logrotate.d/kube-apiserver" }
      - { src: "logrotate/kube-controller-manager", dest: "/etc/logrotate.d/kube-controller-manager" }
      - { src: "logrotate/kube-scheduler", dest: "/etc/logrotate.d/kube-scheduler" }
      - { src: "master/kube-apiserver.service", dest: "{{ systemd_service_dir }}/kube-apiserver.service" }
      - { src: "master/kube-controller-manager.service", dest: "{{ systemd_service_dir }}/kube-controller-manager.service" }
      - { src: "master/kube-scheduler.service", dest: "{{ systemd_service_dir }}/kube-scheduler.service" }
      - { src: "bootstrap-secret/kubelet-bootstrap-secret.yaml", dest: "{{ rbac_dir }}/kubelet-bootstrap-secret.yaml" }

  - name: 启动 kubernetes master节点 三大核心组件，并设置开机启动
    systemd:
      name: "{{ item }}"
      daemon_reload: yes
      state: restarted
      enabled: yes
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler

  - include_tasks: common/check_master_status.yml

  - block:
    - name: 配置 kubelet rbac 文件
      copy:
        src: "kubelet-rbac"
        dest: "{{ rbac_dir }}"
        mode: 0644

    - name: 渲染 kubelet rbac 文件
      template:
        src: "{{ item.src }}.j2"
        dest: "{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - { src: "kubelet/kubelet-config-rbac.yaml", dest: "{{ rbac_dir }}/kubelet-rbac/kubelet-config-rbac.yaml" }

    - name: 创建 kubelet rbac 资源
      command: >
        kubectl apply -f "{{ rbac_dir }}/kubelet-rbac"
      environment:
        KUBECONFIG: "{{ kubernetes_etc_dir }}/admin.conf"
    delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_masters']) | unique | first }}"
    run_once: true

  - name: 创建 kubelet bootstrap secret
    command: >
      kubectl apply -f {{ rbac_dir }}/kubelet-bootstrap-secret.yaml
    environment:
      KUBECONFIG: "{{ kubernetes_etc_dir }}/admin.conf"
    run_once: true
    delegate_to: "{{ groups['masters'][0] }}"
  when: "inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']) | unique)"
