- name: 二进制安装，配置 kubeadm-flags.env
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - { src: "kubelet/kubeadm-flags.env", dest: "/var/lib/kubelet/kubeadm-flags.env" }

- name: 启动 kubelet，并设置开机启动
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    state: restarted
    enabled: yes
  with_items:
    - kubelet
    # - kube-proxy

- name: 等待 kubelet 启动
  wait_for:
    host: "127.0.0.1"
    port: "{{ item }}"
    state: started
    delay: 2
    connect_timeout: 2
    timeout: 15
  with_items:
    - 10248
    # - 10256
