- hosts: kube_cluster
  become: true
  gather_facts: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
  - { role: k8s-network/flannel, when: "container_network == 'flannel'" }
  - { role: k8s-network/calico/install, when: "container_network == 'calico'" }
