# add_nodes
- hosts: add_nodes
  become: true
  serial: 2
  gather_facts: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    add_nodes_task: true
  roles:
  - { role: prepare/kernel }
  - { role: prepare/check-environment }
  - { role: prepare/chrony, when: "groups['chrony']|length > 0" }
  - { role: prepare/initialize }
  - { role: container-runtime }
  - { role: cluster-ops/add/worker }
  - { role: kubernetes }

- hosts:
  - kube_cluster
  become: true
  gather_facts: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
  - name: 更新 hosts
    include_tasks: "{{ inventory_dir }}/roles/cluster-ops/update_host.yml"

  - name: 更新 endpoit
    include_tasks: "{{ inventory_dir }}/roles/cluster-ops/update_endpoint.yml"
