- block:
  - name: 所有 kube_cluster 节点加载依赖镜像
    command: >
      {% if container_runtime == 'docker' -%}
        docker load -i {{ cache_dir }}/images/all.tar.gz
      {% elif container_runtime == 'containerd' -%}
        ctr -n=k8s.io images import {{ cache_dir }}/images/all.tar.gz
      {%- endif -%}

  - name: 所有 kube_cluster 节点创建所需目录
    file:
      name: "{{ item }}"
      state: directory
      mode: 0644
    with_items:
    - "{{ ansible_env.HOME }}/.kube/"
    - "{{ kubernetes_etc_dir }}"
    - "{{ manifest_dir }}"
    - "{{ cni_etc_dir }}"
    - "{{ systemd_service_dir }}/kubelet.service.d"
    - "{{ kubelet_data_dir }}"
    - "{{ kube_proxy_data_dir }}"
    - "{{ kubernetes_log_dir }}/kubelet"

  - name: 所有 kube_cluster 节点渲染相关配置文件
    template:
      src: "{{ item.src }}.j2"
      dest: "{{ item.dest }}"
      owner: "root"
      group: "root"
      mode: "0644"
    with_items:
      - { src: "kubelet/10-kubeadm.conf", dest: "{{ systemd_service_dir }}/kubelet.service.d/10-kubeadm.conf" }
      - { src: "kubelet/11-container-runtime.conf", dest: "{{ systemd_service_dir }}/kubelet.service.d/11-container-runtime.conf" }
      - { src: "kubelet/12-cgroup.conf", dest: "{{ systemd_service_dir }}/kubelet.service.d/12-cgroup.conf" }
      - { src: "kubelet/kubelet.service", dest: "{{ systemd_service_dir }}/kubelet.service" }
      - { src: "kubelet/kubelet-config.yml", dest: "{{ kubelet_data_dir }}/config.yaml" }
      - { src: "kube-proxy/kube-proxy-config.yaml", dest: "{{ kube_proxy_data_dir }}/config.yaml" }

  - name: 配置 kubelet-pre-start.sh
    template:
      src: "{{ item.src }}.j2"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0755
    with_items:
      - { src: "kubelet/kubelet-pre-start.sh", dest: "/usr/bin/kubelet-pre-start.sh" }

  - name: 生成 {{ lb_mode }} static pod 配置文件
    when: 'lb_mode == "kube-vip" or lb_mode == "kube-lvscare"'
    template:
      src: "{{ item.src }}.j2"
      dest: "{{ item.dest }}"
      owner: "root"
      group: "root"
      mode: "0644"
    with_items:
      # kube-vip
      - { src: "kube-vip/lb-kube-vip.yaml", dest: "{{ manifest_dir }}/lb-kube-vip.yaml", lb: "kube-vip" }
      # kube-lvscare
      - { src: "kube-lvscare/lb-kube-lvscare.yaml", dest: "{{ manifest_dir }}/lb-kube-lvscare.yaml", lb: "kube-lvscare" }

  ## 1.15.12 匿名用户报错：
  # https://happywzy.top/k8s-master-jie-dian-notready/
  # kubectl create clusterrolebinding test:anonymous --clusterrole=cluster-admin --user=system:anonymous
  ## 安装 flannel 失败：
  # rm -f /etc/cni/net.d/99-containerd-net.conflist
  # systemctl stop kubelet && ip link del cni0 && systemctl restart kubelet
  - name: 所有 kube_cluster 节点渲染相关配置文件
    when: kube_version is version('1.17.0', '<=')
    template:
      src: "{{ item.src }}.j2"
      dest: "{{ item.dest }}"
      owner: "root"
      group: "root"
      mode: "0644"
    with_items:
      # 不需要创建,static pod 会初始化失败
      - { src: "cni-plugin/10-containerd-net.conflist", dest: "{{ cni_etc_dir }}/99-containerd-net.conflist" }
