# etcd certificates
etcd_ca: "{{ etcd_pki_dir }}/ca.crt"
etcd_ca_key: "{{ etcd_pki_dir }}/ca.key"
etcd_cert_server: "{{ etcd_pki_dir }}/server.crt"
etcd_cert_server_key: "{{ etcd_pki_dir }}/server.key"
etcd_cert_client: "{{ etcd_pki_dir }}/client.crt"
etcd_cert_client_key: "{{ etcd_pki_dir }}/client.key"
etcd_cert_peer: "{{ etcd_pki_dir }}/peer.crt"
etcd_cert_peer_key: "{{ etcd_pki_dir }}/peer.key"
etcd_cert_apiserver_server: "{{ k8s_pki_dir }}/apiserver-etcd-client.crt"
etcd_cert_apiserver_server_key: "{{ k8s_pki_dir }}/apiserver-etcd-client.key"
etcd_cert_healthcheck_client: "{{ etcd_pki_dir }}/healthcheck-client.crt"
etcd_cert_healthcheck_client_key: "{{ etcd_pki_dir }}/healthcheck-client.key"

# kubernetes certificates master nodes
kubernetes_ca: "{{ k8s_pki_dir }}/ca.crt"
kubernetes_ca_key: "{{ k8s_pki_dir }}/ca.key"
apiserver_cert: "{{ k8s_pki_dir }}/apiserver.crt"
apiserver_cert_key: "{{ k8s_pki_dir }}/apiserver.key"
apiserver_kubelet_cert: "{{ k8s_pki_dir }}/apiserver-kubelet-client.crt"
apiserver_kubelet_cert_key: "{{ k8s_pki_dir }}/apiserver-kubelet-client.key"
controller_cert_manager: "{{ k8s_pki_dir }}/kube-controller-manager.crt"
controller_cert_manager_key: "{{ k8s_pki_dir }}/kube-controller-manager.key"
scheduler_cert: "{{ k8s_pki_dir }}/kube-scheduler.crt"
scheduler_cert_key: "{{ k8s_pki_dir }}/kube-scheduler.key"
front_ca: "{{ k8s_pki_dir }}/front-proxy-ca.crt"
front_ca_key: "{{ k8s_pki_dir }}/front-proxy-ca.key"
front_client: "{{ k8s_pki_dir }}/front-proxy-client.crt"
front_client_key: "{{ k8s_pki_dir }}/front-proxy-client.key"
admin: "{{ k8s_pki_dir }}/admin.crt"
admin_key: "{{ k8s_pki_dir }}/admin.key"
sa_public_key: "{{ k8s_pki_dir }}/sa.pub"
sa_private_key: "{{ k8s_pki_dir }}/sa.key"
