setup_way: "{%- if setup is undefined -%}binary{% else%}{{ setup }}{% endif %}"
startup_way: "{%- if startup is undefined -%}kubeadm{% else%}{{ startup }}{% endif %}"
install_way: "{%- if install is undefined -%}command{% else%}{{ install }}{% endif %}"
certs_way: "{%- if certs is undefined -%}kube-certs{% else%}{{ certs }}{% endif %}"
cfssl_convert: "{%- if (convert is defined and convert | bool) or (startup_way == 'kubeadm') -%}true{% else%}false{% endif %}"
etcd_local: "{%- if (etcd is undefined) or (etcd == 'local') -%}true{% else%}false{% endif %}"
