# keepalived 参数
vip_interface: "{{ iface }}"
# 区分多个instance的VRRP组播，同网段不能重复，取值在0-255之间
# 因项目已设置vrrp报文单播模式，所以这个ROUTER_ID 即便同网段里面有重复也没关系
virtual_router_id: "66"
keepalived_password: "e82#Kdr?59D0/HU"

# haproxy监控绑定端口
# haproxy负载均衡算法，常见如下：
# "roundrobin": 基于服务器权重的轮询
# "leastconn": 基于服务器最小连接数
# "source": 基于请求源IP地址
# "uri": 基于请求的URI
lb_haproxy_balance_alg: "leastconn"

# haproxy监控绑定端口
lb_envoy_admin_address_port: 9090

# Kubernetes  高可用配置
lb_apiserver_ip: "{{ vip_address }}"
# lb_secure_port: 8443
lb_secure_port: "{%- if lb_mode == 'kube-vip' or lb_mode == 'kube-lvscare' -%}6443{%- else -%}8443{%- endif %}"
lb_healthcheck_port: 8081
single_api_address: "{{ groups['kube_masters'] | difference(groups['delete_masters']) | unique | first }}:6443"
# lb_api_address: "{%- if lb_mode == 'kube-vip' or lb_mode == 'kube-lvscare' -%}{{ hostvars[groups['kube_masters'] | difference(groups['delete_masters']) | unique | first]['ansible_' + iface].ipv4.address }}{%- else -%}{{ vip_address }}{%- endif %}:{{ lb_secure_port }}"
lb_api_address: "{{ vip_address }}:{{ lb_secure_port }}"
api_address: "{%- if groups['kube_masters'] | length == 1 -%}{{ single_api_address }}{%- else -%}{{ lb_api_address }}{%- endif %}"
api_url: "https://{{ kube_master_external_domain[0] }}:{%- if groups['kube_masters'] | length == 1 or lb_mode == 'kube-vip' or lb_mode == 'kube-lvscare' -%}6443{%- else -%}8443{%- endif %}"
