- name: 二进制安装 cfssl、cfssl-certinfo 和 cfssljson
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: "{{ cache_dir }}/binary/cfssl/", dest: "/usr/local/bin/"}

- block:
  - name: 配置 etcd 证书相关参数
    set_fact:
      certs: "{{ cfssl_etcd_certs }}"

  - name: 创建 etcd 相关证书
    include_tasks: "_create.yml"

  - name: 配置 kubernetes master 证书相关参数
    set_fact:
      certs: "{{ cfssl_master_certs }}"

  - name: 创建 kubernetes master 节点相关证书
    include_tasks: "_create.yml"
  run_once: true
  delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_etcds']) | difference(groups['delete_masters']) | unique | first }}"

- name: 配置 kubernetes worker 证书相关参数
  set_fact:
    certs: "{{ cfssl_worker_certs }}"

- name: 创建 kubernetes worker 节点相关证书
  include_tasks: "_create.yml"
