- name: 渲染 kube-proxy 配置文件
  when: "inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']))"
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - { src: "kube-proxy/kubeproxy-cm.yml", dest: "{{ addons_dir }}/kube-proxy/kubeproxy-cm.yml" }
    - { src: "kube-proxy/kubeproxy-ds.yml", dest: "{{ addons_dir }}/kube-proxy/kubeproxy-ds.yml" }

- name: 部署 kube-proxy
  changed_when: true
  command: >
    kubectl apply -f "{{ addons_dir }}/kube-proxy/"
  environment:
    KUBECONFIG: "{{ kubernetes_etc_dir }}/admin.conf"
  delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_masters']) | unique | first }}"
  run_once: true
