- block:
  - block:
    - name: 创建 kube-coredns 组件配置文件目录
      file:
        path: "{{ item }}"
        state: directory
        mode: 0644
      with_items:
      - "{{ addons_dir }}/coredns"

    - name: 渲染 coredns 配置文件
      when: "inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']))"
      template:
        src: "{{ item.src }}.j2"
        dest: "{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - { src: "coredns/coredns.yaml", dest: "{{ addons_dir }}/coredns/coredns.yaml" }
        - { src: "coredns/autoscale.yaml", dest: "{{ addons_dir }}/coredns/autoscale.yaml" }
        - { src: "coredns/nodelocaldns.yaml", dest: "{{ addons_dir }}/coredns/nodelocaldns.yaml" }
    when: "inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']))"

  - name: 部署 coredns
    changed_when: true
    command: >
      kubectl apply -f "{{ addons_dir }}/coredns/"
    environment:
        KUBECONFIG: "{{ kubernetes_etc_dir }}/admin.conf"
    register: apply_coredns
    until: apply_coredns.rc == 0
    retries: 3
    delay: "{{ retry_stagger }}"
    run_once: "{{ enable_run_once | default(true) }}"
    delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_masters']) | unique | first }}"
  when: skip_coredns | bool
