- name: 渲染 coredns 配置文件
  when: "inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']))"
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - { src: "coredns/coredns.yaml", dest: "{{ addons_dir }}/coredns/coredns.yaml" }
    - { src: "coredns/autoscale.yaml", dest: "{{ addons_dir }}/coredns/autoscale.yaml" }
    - { src: "coredns/nodelocaldns.yaml", dest: "{{ addons_dir }}/coredns/nodelocaldns.yaml" }

- name: 部署 coredns
  shell: >
    kubectl apply -f "{{ addons_dir }}/coredns/"
  environment:
    KUBECONFIG: "{{ kubernetes_etc_dir }}/admin.conf"
  delegate_to: "{{ groups['kube_masters'][0] }}"
  run_once: true
