- name: 获取 kubernetes master 节点相关 kubeconfig 文件
  slurp:
    src: "{{ item }}"
  with_items:
    - "{{ kubernetes_etc_dir }}/admin.conf"
    - "{{ kubernetes_etc_dir }}/controller-manager.conf"
    - "{{ kubernetes_etc_dir }}/scheduler.conf"
  register: slurp_kubernetes_kube_config
  run_once: true
  delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_etcds']) | difference(groups['delete_masters']) | unique | first }}"

- name: 分发 kubernetes master 相关证书到 master 节点
  copy:
    dest: "{{ item.source }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  with_items: "{{ slurp_kubernetes_kube_config.results }}"
  when:
    - inventory_hostname in groups['kube_masters']
    - inventory_hostname != (groups['kube_masters'] | difference(groups['delete_etcds']) | difference(groups['delete_masters']) | unique | first)
