- name: 获取 kubernetes master 节点相关 kubeconfig 文件
  slurp:
    src: "{{ item }}"
  with_items:
    - "{{ kubernetes_etc_dir }}/admin.conf"
    - "{{ kubernetes_etc_dir }}/controller-manager.conf"
    - "{{ kubernetes_etc_dir }}/scheduler.conf"
  register: slurp_master_kubeconfig
  run_once: true
  delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_masters']) | unique | first }}"

- name: 分发 kubernetes master 相关证书到 master 节点
  copy:
    dest: "{{ item.source }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  with_items: "{{ slurp_master_kubeconfig.results }}"
  when:
    - inventory_hostname in groups['kube_masters']
    - inventory_hostname != (groups['kube_masters'] | difference(groups['delete_masters']) | unique | first)

- name: 获取 bootstrap-kubelet.conf kubeconfig 文件
  slurp:
    src: "{{ item }}"
  with_items:
    - "{{ kubernetes_etc_dir }}/bootstrap-kubelet.conf"
  register: slurp_bootstrap_kubeconfig
  run_once: true
  delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_masters']) | unique | first }}"

- name: 分发 bootstrap-kubelet.conf kubeconfig 文件
  copy:
    dest: "{{ item.source }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  with_items: "{{ slurp_bootstrap_kubeconfig.results }}"
  when:
    - groups['kube_cluster'] | difference(groups['delete_masters']) | difference(groups['delete_nodes']) | unique | length > 1
    - "inventory_hostname in (groups['kube_cluster'] | difference(groups['delete_masters']) | difference(groups['delete_nodes']) | unique)"
    - inventory_hostname != (groups['kube_masters'] | difference(groups['delete_masters']) | unique | first)

- name: 删除 kubernetes master 节点其他证书
  when: (certs_way == 'openssl') or (certs_way == 'cfssl')
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ controller_cert_manager }}"
    - "{{ controller_cert_manager_key }}"
    - "{{ scheduler_cert }}"
    - "{{ scheduler_cert_key }}"
    - "{{ admin }}"
    - "{{ admin_key }}"
  run_once: true
  delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_masters']) | unique | first }}"
