- name: etcd_initial_cluster_state
  set_fact:
    etcd_initial_cluster_state: existing

- name: 新节点部署服务
  when:
    - "groups['add_etcds']|length > 0"
    - inventory_hostname in (groups['add_etcds'] | difference(groups['delete_etcds']) | unique )
  include_role:
    name: "{{ inventory_dir }}/roles/etcd"

- block:
  - name: 获取 etcd member 状态
    command: >-
      etcdctl --endpoints {{ etcd_servers }} \
      --cacert {{ etcd_ca }} \
      --key  {{ etcd_cert_healthcheck_client_key }} \
      --cert {{ etcd_cert_healthcheck_client }} \
      member list | grep {{ inventory_hostname }};
    environment:
      ETCDCTL_API: 3
    register: get_etcd_member

  - name: 新节点 加入 etcd 集群中
    when: get_etcd_member.stdout | length == 0
    changed_when: true
    command: >-
      etcdctl --endpoints {{ etcd_servers }} \
      --cacert {{ etcd_ca }} \
      --key  {{ etcd_cert_healthcheck_client_key }} \
      --cert {{ etcd_cert_healthcheck_client }} \
      member add {{ hostvars[inventory_hostname].ansible_hostname | lower }} --peer-urls={{ etcd_listen_peer_urls }}
    environment:
      ETCDCTL_API: 3
  delegate_to: "{{ groups['kube_etcds'] | difference(groups['delete_etcds']) | unique | first }}"
  when: inventory_hostname in (groups['add_etcds'] | difference(groups['delete_etcds']) | unique )
