- name: 创建 {{ out_item.item.dir }}/{{ out_item.item.name }}.key 私钥
  when: not out_item.stat.exists
  shell: >
    openssl genrsa -out {{ out_item.item.dir }}/{{ out_item.item.name }}.key {{ cert_key_size }}

- name: 判断 {{ out_item.item.dir }}/{{ out_item.item.name }}.crt 证书是否存在
  stat:
    path: "{{ out_item.item.dir }}/{{ out_item.item.name }}.crt"
  register: check_cert_crt_files

- block:
  - name: 签发 {{ out_item.item.dir }}/{{ out_item.item.name }}.crt CA 根证书
    when: out_item.item.kind == "ca"
    shell: >-
      openssl req -x509 -new -nodes -extensions {{ out_item.item.kind }} \
        -subj "/CN={{ out_item.item.cn }}/{%- if out_item.item.org is defined -%}O={{ out_item.item.org }}{% else %}{%- endif -%}" \
        -config {{ kube_openssl_cnf }}  \
        -key {{ out_item.item.dir }}/{{ out_item.item.name }}.key \
        -out {{ out_item.item.dir }}/{{ out_item.item.name }}.crt \
        -days {{ ca_certs_expired }}

  - name: 创建 {{ out_item.item.dir }}/{{ out_item.item.name }}.csr 证书请求文件
    when: out_item.item.kind != "ca"
    shell: >-
      openssl req -new \
        -subj "/CN={{ out_item.item.cn }}/{%- if out_item.item.org is defined -%}O={{ out_item.item.org }}{% else %}{%- endif -%}" \
        -key {{ out_item.item.dir }}/{{ out_item.item.name }}.key \
        -out {{ out_item.item.dir }}/{{ out_item.item.name }}.csr

  - name: 生成 {{ out_item.item.dir }}/{{ out_item.item.name }}.crt 证书
    when: out_item.item.kind != "ca"
    shell: >-
      openssl x509 -req -CAcreateserial -extensions {{ out_item.item.kind }} \
        {% if 'etcd-ca' == out_item.item.parent_ca -%}
        -extfile {{ etcd_openssl_cnf }} \
        -CA {{ etcd_ca }} \
        -CAkey {{ etcd_ca_key }} \
        {% elif 'kubernetes-ca' == out_item.item.parent_ca -%}
        -extfile {{ kube_openssl_cnf }} \
        -CA {{ kubernetes_ca }} \
        -CAkey {{ kubernetes_ca_key }} \
        {% elif 'kubernetes-front-proxy-ca' == out_item.item.parent_ca -%}
        -extfile {{ kube_openssl_cnf }} \
        -CA {{ front_ca }} \
        -CAkey {{ front_ca_key }} \
        {% endif -%}
        -in {{ out_item.item.dir }}/{{ out_item.item.name }}.csr \
        -out {{ out_item.item.dir }}/{{ out_item.item.name }}.crt \
        -days {{ certs_expired }}
  when: not check_cert_crt_files.stat.exists
