
- block:
  - name: 配置 etcd 和 kubernetes master 证书相关参数
    set_fact:
      certs: "{{ master_certs }}"

  - name: 创建 kubernetes master 节点相关证书
    include_tasks: "_create.yml"
  run_once: true
  delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_etcds']) | difference(groups['delete_masters']) | unique | first }}"

- name: 配置 kubernetes worker 证书相关参数
  set_fact:
    certs: "{{ worker_certs }}"

- name: 创建 kubernetes worker 节点相关证书
  include_tasks: "_create.yml"
