- block:
  - name: 所有节点创建备份目录
    file:
      name: "{{ item }}"
      state: directory
      mode: 0644
    with_items:
    - "{{ kubernetes_etc_dir }}/backup-k8s/logrotate"

  - name: 集群内节点备份 master 三大组件 service 文件
    copy:
      src: "{{ item }}"
      dest: "{{ kubernetes_etc_dir }}/backup-k8s/service"
      mode: 0644
      remote_src: yes
    with_items:
    - "{{ systemd_service_dir }}/kube-apiserver.service"
    - "{{ systemd_service_dir }}/kube-controller-manager.service"
    - "{{ systemd_service_dir }}/kube-scheduler.service"

  - name: 集群内节点备份 master 三大组件 logrotate 文件
    copy:
      src: "{{ item }}"
      dest: "{{ kubernetes_etc_dir }}/backup-k8s/logrotate"
      mode: 0644
      remote_src: yes
    with_items:
    - "/etc/logrotate.d/kube-apiserver"
    - "/etc/logrotate.d/kube-controller-manager"
    - "/etc/logrotate.d/kube-scheduler"
  when: inventory_hostname in (groups['kube_masters'] | difference(groups['delete_masters']) | unique)
