- name:  卸载 ntp
  package:
    name: ntp
    state: absent

- name: debug
  debug:
    msg: "安装 chrony, 可能需要一定时间。。"
  run_once: true

- name: 获取 chrony rpm 文件包
  find:
    paths: "{{ cache_dir }}/chrony/"
    patterns: "*.rpm"
    # use_regex: true
  register: get_chrony_rpm_files

- name: 离线安装 chrony
  yum:
    name: "{{ item.path }}"
    state: present
  with_items: "{{ get_chrony_rpm_files['files'] }}"

- block:
  - name: 配置 chrony server
    template:
      src: server-centos.conf.j2
      dest: /etc/chrony.conf
      mode: 0644

  - name: 启动 chrony server
    service: name=chronyd state=restarted enabled=yes
  when: 'inventory_hostname == groups.chrony[0]'

- block:
  - name: 配置 chrony client
    template:
      src: client-centos.conf.j2
      dest: /etc/chrony.conf
      mode: 0644
    when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'

  - name: 启动 chrony client
    service:
      name: chronyd
      state: restarted
      enabled: yes
    when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'
  when: 'inventory_hostname != groups.chrony[0]'
