- name: 校验节点系统架构
  assert:
    that: ansible_machine in [ 'x86_64' ]
    msg: "节点：{{ inventory_hostname }} {{ ansible_machine }} 系统指令集不支持使用本脚本升级内核"

- name: 校验节点操作系统
  assert:
    that: ansible_distribution in [ 'CentOS','OracleLinux','RedHat',"Amazon" ]
    msg: "节点：{{ inventory_hostname }} {{ ansible_distribution }} 系统不支持使用本脚本升级内核"

- name: 执行命令获取内核版本
  shell: uname -r
  register: get_kernel_version

- name: 获取系统当前使用内核版本
  set_fact:
    fact_kernel_version: "{{ get_kernel_version.stdout.split('.el7')[0] }}"

- name: 获取内核参数
  debug:
    var: get_kernel_version.stdout

- include_tasks: online.yml
  when: install_online is defined and install_online | bool

- include_tasks: offline.yml

- name: 设置默认内核为最新安装版本
  shell: "grub2-set-default 0 && grub2-mkconfig -o /boot/grub2/grub.cfg"
  ignore_errors: true

- name: 获取默认内核版本
  shell: "grubby --default-kernel"
  ignore_errors: true

- name: 开启 User namespaces
  shell: grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
  ignore_errors: true

- name: 卸载 3.10 版本 kernel
  shell: "yum remove -y kernel*3.10*"

- name: 需手动重启服务器
  debug:
    msg: >-
      节点：{{ inventory_hostname }}，
      内核已升级完成，
      请手动执行 reboot -f 重启该服务器。
