- block:
  - name: debug
    debug:
      msg: "更新 kernel, 可能需要一定时间。。"
    run_once: true

  - name: 离线安装 kernel
    shell: >-
      rpm -Uvh --nodeps --force {{ cache_dir }}/kernel/*.rpm
  when: 'fact_kernel_version not in kernel_offlie_version'
