- name: 添加 kubectl kubeadm 命令自动补全
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    regexp: "{{ item }} completion"
    line: "source <({{ item }} completion bash)"
  with_items:
    - kubectl
    - kubeadm

- name: 当前会话加载 kubectl kubeadm 命令，并自动补全
  changed_when: true
  command: >
    {{ item }} completion bash > /etc/bash_completion.d/{{ item }};
    source {{ ansible_env.HOME }}/.bash_profile
  args:
    executable: /bin/bash
  with_items:
    - kubectl
    - kubeadm

- name: 所有 kube_cluster 节点创建所需目录
  file:
    name: "{{ item }}"
    state: directory
    mode: 0644
  with_items:
  - "{{ ansible_env.HOME }}/.kube/"
  - "{{ kubernetes_etc_dir }}"
  - "{{ manifest_dir }}"
  - "{{ cni_etc_dir }}"
  - "{{ systemd_service_dir }}/kubelet.service.d"
  - "{{ kubelet_pki_dir }}"
  - "{{ kubernetes_log_dir }}/kubelet"
  - "{{ kubernetes_log_dir }}/kube-proxy"

- name: restore kubernetes
  include_tasks: restore.yml

- name: 普通用户配置集群访问权限
  include_tasks: "{{ inventory_dir }}/roles/k8s-setup/tasks/common/normal-user-admission.yml"
