- block:
  - name: 停止 kubelet 运行
    systemd:
      name: kubelet
      daemon_reload: yes
      state: restarted
      enabled: yes
    register: stop_kubelet_result
    failed_when: false

  - name: 读取 kubernetes 备份数据
    find:
      paths: "{{ (playbook_dir + '/cluster-backup') | realpath  }}"
      patterns: "{{ inventory_hostname }}-kubernetes.orig.*"
    register: kubernetes_back_dirs
    delegate_to: localhost

  - name: 校验 kubernetes 备份文件是否存在
    assert:
      that: kubernetes_back_dirs.files|length >= 1
      msg: "未获取到节点：{{ inventory_hostname }} 的任何备份文件，请检查目录：{{ (playbook_dir + '/cluster-backup') | realpath  }} 中是否有该节点备份文件。"

  - name: 获取 kubernetes 最新备份目录
    set_fact:
      kubernetes_latest_back_dir: "{{ kubernetes_back_dirs.files | sort(attribute='ctime',reverse=true) | first }}"

  - name: 清理相关目录
    failed_when: false
    file:
      name: "{{ item }}"
      state: absent
    with_items:
    - "{{ kubernetes_etc_dir }}"
    - "{{ kubelet_data_dir }}"
    - "{{ systemd_service_dir }}/kubelet.service.d"
    - "{{ ansible_env.HOME }}/.kube"

  - name: 创建 kubernetes 相关目录
    file:
      name: "{{ item }}"
      state: directory
      mode: 0644
    with_items:
    - "{{ kubernetes_etc_dir }}"
    - "{{ kubelet_data_dir }}"
    - "{{ systemd_service_dir }}/kubelet.service.d"
    - "{{ ansible_env.HOME }}/.kube"
    - /backup-cluster-tmp

  - name: 分发备份文件到对应节点
    copy:
      src: "{{ kubernetes_latest_back_dir.path }}"
      dest: /backup-cluster-tmp
      mode: 0644

  - name: 还原备份文件
    unarchive:
      src: "/backup-cluster-tmp/{{ kubernetes_latest_back_dir.path|basename }}"
      dest: "{{ kubernetes_etc_dir }}"
      remote_src: yes

  - name: 恢复集群内节点各服务 service 文件
    copy:
      src: "{{ kubernetes_etc_dir }}/backup-k8s/service/"
      dest: "{{ systemd_service_dir }}"
      mode: 0644
      remote_src: yes

  - name: 恢复集群内节点 kubelet 数据文件
    copy:
      src: "{{ kubernetes_etc_dir }}/backup-k8s/kubelet/"
      dest: "{{ kubelet_data_dir }}"
      mode: 0644
      remote_src: yes

  - name: systemctl 安装恢复
    include_tasks: systemctl.yml
    when: startup != 'kubeadm'

  - name: 启动 kubelet
    systemd:
      name: "{{ item }}"
      daemon_reload: yes
      state: restarted
      enabled: yes
    with_items:
      - kubelet

  - name: 等待 kubelet 件启动
    wait_for:
      host: "127.0.0.1"
      port: "{{ item }}"
      delay: 5
      connect_timeout: 60
      timeout: 300
    with_items:
      - "10250"

  - name: 获取 kubeconfig admin 文件
    slurp:
      src: "{{ item }}"
    with_items:
      - "{{ kubernetes_etc_dir }}/admin.conf"
    register: slurp_kubeconfig
    run_once: true
    delegate_to: "{{ groups['kube_masters'] | difference(groups['delete_etcds']) | difference(groups['delete_masters']) | unique | first }}"

  - name: 配置 kubeconfig admin 文件到 $HOME/.kube/config
    copy:
      dest: "{{ ansible_env.HOME }}/.kube/config"
      content: "{{ item.content | b64decode }}"
      owner: root
      group: root
      mode: 0600
    no_log: true
    with_items: "{{ slurp_kubeconfig.results }}"
  when: inventory_hostname in groups['kube_cluster'] | difference(groups['delete_etcds']) | difference(groups['delete_masters']) | difference(groups['delete_nodes'])
